name: Setup Node & Install

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Enable Corepack
      run: corepack enable
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
